version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/first-repo/ # should be changed the destination that should be put in

hooks:
  # During the AfterInstall deployment lifecycle event, run the commands
  #   in the script specified in "location".
  AfterInstall:
    - location: afterInstall.sh
      runas: ubuntu
      timeout: 300
